# render.yaml (partial - focus on startCommand)

services:
  - type: web
    name: noi-extraction-api # Or your chosen name
    env: python
    runtime: python
    plan: free # Or your chosen plan
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    # --- VERIFY THIS LINE ---
    startCommand: uvicorn main_backend:app --host 0.0.0.0 --port $PORT
    # --- END VERIFY ---
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        sync: false
    healthCheckPath: /health
